create schema exmgr;

drop table if exists exmgr.daily_user_metric;
create table exmgr.daily_user_metric (
  id bigint not null default unique_rowid(),
  report_date date not null,
  media_source text not null,
  cost double precision default 0,
  impressions bigint default 0,
  clicks bigint default 0,
  installs bigint default 0,
  nru bigint default 0,
  dau bigint default 0,
  pu bigint default 0,
  npu bigint default 0,
  rev double precision default 0,
  revnpu double precision default 0,
  ruser01 bigint default 0,
  ruser03 bigint default 0,
  ruser07 bigint default 0,
  ruser14 bigint default 0,
  ruser21 bigint default 0,
  ruser30 bigint default 0,
  ruser60 bigint default 0,
  ruser90 bigint default 0,
  revrpi01 double precision default 0,
  revrpi03 double precision default 0,
  revrpi07 double precision default 0,
  revrpi14 double precision default 0,
  revrpi21 double precision default 0,
  revrpi30 double precision default 0,
  revrpi60 double precision default 0,
  revrpi90 double precision default 0,
  revrpi120 double precision default 0,
  revrpi150 double precision default 0,
  revrpi180 double precision default 0,
  revnru01 double precision default 0,
  revnru03 double precision default 0,
  revnru07 double precision default 0,
  revnru14 double precision default 0,
  revnru21 double precision default 0,
  revnru30 double precision default 0,
  revnru60 double precision default 0,
  revnru90 double precision default 0,
  revnru120 double precision default 0,
  revnru150 double precision default 0,
  revnru180 double precision default 0,
  primary key (id)
);
create unique index daily_user_metric_uniq_idx on exmgr.daily_user_metric(report_date, media_source);